# Generated by Django 3.0.7 on 2020-06-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djasana', '0020_auto_20191013_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(blank=True, choices=[], max_length=16, null=True),
        ),
    ]
