# Generated by Django 2.2.13 on 2020-06-23 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djasana', '0021_adds_custom_field_has_notifications_enabled'),
        ('djasana', '0021_auto_20200623_1917'),
    ]

    operations = [
    ]
